include:
  - ./external-api/compose.external-api.yaml

services:
  web1:
    extends:
      file: compose.common.yaml
      service: web
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.38-debian
    restart: on-failure:5
    environment:
      - MYSQL_DATABASE=my_database
      - MYSQL_ROOT_PASSWORD=root
    # Ajuda a economizar tempo e recursos nos testes, tudo o que for fazer bastante IO..
    tmpfs:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
