FROM node:22.12.0-slim

RUN apt update && \
    apt install -y curl && \
    npm install -g nodemon

COPY start.sh /
RUN chmod +x /start.sh

USER node

WORKDIR /home/node/app

COPY package.json ./
RUN npm install

EXPOSE 3000

CMD ["/start.sh"]