ARG NODE_VERSION=22.12.0
ARG NODMON_VERSION=3.1.7

FROM node:${NODE_VERSION}-slim

RUN apt update && \
    apt install -y curl && \
    npm install -g nodemon@${NODMON_VERSION}

COPY start.sh /
RUN chmod +x /start.sh

USER node

WORKDIR /home/node/app

COPY package.json ./
RUN npm install

EXPOSE 3000

CMD ["/start.sh"]