include:
  - ./external-api/compose.external-api.yaml

services:
  app1: 
    extends:
      file: ./compose.common.yaml
      service: app
    profiles: [dev, production]
    ports:
      - 3000:3000

  app2:
    profiles: [production]
    extends:
      file: ./compose.common.yaml
      service: app
    # ports:
    #   - 3001:3000

  nginx:
    image: nginx:1.25.3-alpine
    profiles: [production]
    restart: always
    ports:
      - 4000:80
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
    profiles: [debug-db]
    ports:
      - 8080:80
    depends_on:
      db: 
        condition: service_healthy

  db: 
    image: mysql:8.0.38-debian
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] # Comando para verificar se o servidor MySQL está respondendo
      interval: 10s # Intervalo entre cada verificação de saúde
      timeout: 5s # Tempo máximo para a execução do comando de verificação
      retries: 5 # Número de tentativas antes de considerar o contêiner como não saudável
      start_period: 5s # Tempo de espera após o início do contêiner antes de iniciar as verificações de saúde

