### Login
# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "john@partner.com",
  "password": "123456"
}

###
 @tokenPartner1 = {{login.response.body.token}}

### Cadastro de Partners
POST http://localhost:3000/api/partners/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@partner.com",
  "password": "123456",
  "company_name": "Company Name"
}

### Cadastro de Customers

POST http://localhost:3000/api/customers/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@customer.com",
  "password": "123456",
  "phone": "1234567890",
  "address": "Rua 123, Centro, Cidade"
}

### Cadastro de Eventos de Partners

### Create Event
# @name createEvent
POST http://localhost:3000/api/partners/events
Content-Type: application/json
Authorization: Bearer {{ tokenPartner1 }}

{
  "name": "Event Name",
  "description": "Event Description",
  "date": "2025-01-01T00:00:00",
  "location": "Event Location"
}

###
 @EventId = {{ createEvent.response.body.id }}

### Listagem de Eventos de Partners

GET http://localhost:3000/api/partners/events
Authorization: Bearer {{ tokenPartner1 }}

### Listagem de Eventos de Partners por ID

GET http://localhost:3000/api/partners/events/{{ EventId }}
Authorization: Bearer {{ tokenPartner1 }}

### Listagem de Eventos

GET http://localhost:3000/api/events

### Listagem de Eventos por ID  

GET http://localhost:3000/api/events/{{ EventId }}


### Criação de tickets
POST http://localhost:3000/api/events/{{ EventId }}/tickets
Content-Type: application/json
Authorization: Bearer {{ tokenPartner1 }}

{
    "num_tickets": 10,
    "price": 100
}
